env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:import/recommended
    - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
    - import
    - react
    - jest
settings:
    "@typescript-eslint/parser":
        - ".ts"
        - ".tsx"
    "import/resolver": 
        typescript:
            alwaysTryTypes: true
rules:
    react/react-in-jsx-scope: off
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - windows
    quotes:
        - error
        - double
    semi:
        - error
        - always
