name: clippy
run-name: Cargo Clippy
on: [push]
jobs:
    clippy:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy
                  override: true
            - run: cd src-tauri; cargo clippy --all-features --all-targets -- -D clippy::all
